{{- if and .Values.global.strategy (eq .Values.global.strategy.type "Rollout") }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: booking-service
  namespace: {{ .Values.global.namespace | default "quick-haul" }}
spec:
  replicas: {{ .Values.global.replicaCount }}
{{- if and .Values.global.strategy (eq .Values.global.strategy.type "Rollout") }}
  strategy:
    blueGreen:
      activeService: booking-service
      previewService: booking-service-preview
      autoPromotionEnabled: true
{{- end }}
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: {{ .Values.global.images.booking }}
        command: ["uvicorn", "services.booking_service.app:app", "--host", "0.0.0.0", "--port", "8003"]
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        ports:
        - containerPort: 8003
        envFrom:
        - configMapRef:
            name: quick-haul-config
        - secretRef:
            name: quick-haul-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: {{ .Values.global.namespace | default "quick-haul" }}
spec:
  type: ClusterIP
  ports:
  - port: 8003
    targetPort: 8003
  selector:
    app: booking-service
{{- if and .Values.global.strategy (eq .Values.global.strategy.type "Rollout") }}
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service-preview
  namespace: {{ .Values.global.namespace | default "quick-haul" }}
spec:
  type: ClusterIP
  ports:
  - port: 8003
    targetPort: 8003
  selector:
    app: booking-service
{{- end }}
