global:
  # namespace: quick-haul (Managed by ArgoCD/Release Namespace)
  replicaCount: 2
  nodePort: 30080
  nfsServer: "172.31.41.176"
  nfsPath: "/mnt/nfs/mongodb"
  
  keycloak:
    issuerUrl: "https://auth.quickhaul.com/auth/realms/QuickHaul"
    clientId: "quickhaul-services"
  
  images:
    auth: "ghcr.io/quickhaultransits/quickhaul-auth:latest"
    booking: "ghcr.io/quickhaultransits/quickhaul-booking:latest"
    location: "ghcr.io/quickhaultransits/quickhaul-location:latest"
    notification: "ghcr.io/quickhaultransits/quickhaul-notification:latest"
    otp: "ghcr.io/quickhaultransits/quickhaul-otp:latest"
    frontend: "ghcr.io/quickhaultransits/quickhaul-frontend:latest"
    mongodb: "mongo:latest"
    redis: "redis:latest"
  
  imagePullSecrets:
    - name: regcred

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
