apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quickhaul-dev-auth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/QuickHaulTransits/quickhaul-config.git
    targetRevision: develop
    path: helm-charts/auth-service
    helm:
      valueFiles:
        - ../global-values.yaml
        - ../environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: quickhaul-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quickhaul-dev-booking
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/QuickHaulTransits/quickhaul-config.git
    targetRevision: develop
    path: helm-charts/booking-service
    helm:
      valueFiles:
        - ../global-values.yaml
        - ../environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: quickhaul-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quickhaul-dev-location
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/QuickHaulTransits/quickhaul-config.git
    targetRevision: develop
    path: helm-charts/location-service
    helm:
      valueFiles:
        - ../global-values.yaml
        - ../environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: quickhaul-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quickhaul-dev-notification
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/QuickHaulTransits/quickhaul-config.git
    targetRevision: develop
    path: helm-charts/notification-service
    helm:
      valueFiles:
        - ../global-values.yaml
        - ../environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: quickhaul-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quickhaul-dev-otp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/QuickHaulTransits/quickhaul-config.git
    targetRevision: develop
    path: helm-charts/otp-service
    helm:
      valueFiles:
        - ../global-values.yaml
        - ../environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: quickhaul-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quickhaul-dev-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/QuickHaulTransits/quickhaul-config.git
    targetRevision: develop
    path: helm-charts/frontend
    helm:
      valueFiles:
        - ../global-values.yaml
        - ../environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: quickhaul-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quickhaul-dev-mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/QuickHaulTransits/quickhaul-config.git
    targetRevision: develop
    path: helm-charts/mongodb
    helm:
      valueFiles:
        - ../global-values.yaml
        - ../environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: quickhaul-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quickhaul-dev-redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/QuickHaulTransits/quickhaul-config.git
    targetRevision: develop
    path: helm-charts/redis
    helm:
      valueFiles:
        - ../global-values.yaml
        - ../environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: quickhaul-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quickhaul-dev-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/QuickHaulTransits/quickhaul-config.git
    targetRevision: develop
    path: helm-charts/quickhaul-infra
    helm:
      valueFiles:
        - ../global-values.yaml
        - ../environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: quickhaul-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quickhaul-dev-keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/QuickHaulTransits/quickhaul-config.git
    targetRevision: develop
    path: helm-charts/keycloak
    helm:
      valueFiles:
        - ../global-values.yaml
        - ../environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: quickhaul-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
