apiVersion: v1
kind: Secret
metadata:
  name: quick-haul-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SECRET_KEY: "hello_welcome_to_quick_haul_transports"
  JWT_SECRET: "hello_welcome_to_quick_haul_transports"
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "password123"
  SMTP_PASSWORD: "xpwh iyqb jtjm uikc"
