apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-nfs-pv-{{ .Values.global.environment }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: {{ .Values.global.nfsPath }}-{{ .Values.global.environment }}
    server: {{ .Values.global.nfsServer }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-nfs-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: mongodb-nfs-pv-{{ .Values.global.environment }}

