apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-nfs
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
reclaimPolicy: Retain
---
{{- $replicas := .Values.global.replicaCount | default 1 -}}
{{- range $i := until (int $replicas) -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-nfs-pv-{{ $.Values.global.environment }}-{{ $i }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "mongodb-nfs"
  nfs:
    path: {{ $.Values.global.nfsPath }}-{{ $.Values.global.environment }}/node-{{ $i }}
    server: {{ $.Values.global.nfsServer }}
---
{{- end -}}
